### ISSUE TITLE
Not displaying information in the UI

### ISSUE THREAD

**Issue by Connor-Knabe** [jfrog/jfrog-visual-studio-extension#10]
The output shows JSON back from XRay but it doesn't seem to be displaying in the UI

I do get this warning as well (don't think it's related because I've had this same issue without this warning)
`[Warn] Package: **** couldn't be parsed due to: XML syntax error on line 1: invalid UTF-8 . Skipping the package dependency.`

Visual Studio Enterprise 2019 Version 16.4.4

![image](https://user-images.githubusercontent.com/4316793/87716571-a1a06a80-c774-11ea-9530-6a7a03f913b5.png)

Any help would be much appreciated, thanks!

**Comment by eyalbe4** [comment]
@Connor-Knabe -
Sorry for the late response here!
Please let us know if this issue is still relevant.

**Comment by Connor-Knabe** [comment]
@eyalbe4 honestly I’m not sure if this is still an issue. I haven’t used JFrog in a while. Closing for now. Feel free to re-open if someone can replicate it.
