### ISSUE TITLE
Not able to connect with Jfrog Instance

### ISSUE THREAD

**Issue by bhupi-cloudeq** [jfrog/jfrog-visual-studio-extension#13]
I have added Jfrog extension in Visual Studio 2019 and not able to connect with Jfrog Instance.

ScreenShot attached

**Edit:**
(redacted image with base platform URL and returned message 404 in the test connection)

![image](https://user-images.githubusercontent.com/73111511/112482469-1b760280-8d9e-11eb-9598-a97bbdeda84a.png)

I used same credentials for VSCode connection got it connected.

**Comment by yahavi** [comment]
@bhupi-cloudeq 
The Xray URL should lead to the Xray endpoint. Could you please try to add the HTTPS protocol and `/xray` at the end of the URL?
https://cloudeq.jfrog.io/xray

Please let me know if that helped.
