### ISSUE TITLE
JFrog Window Crashes Visual Studio 2019

### ISSUE THREAD

**Issue by app2eds** [jfrog/jfrog-visual-studio-extension#15]
I recently installed and configured the JFrog extension in Visual Studio 2019.  If I open a project with dependencies that have no JFrog issues, everything is fine.  If I open a project where I know some of the dependencies have vulnerabilities, as soon as I open the JFrog window, Visual Studio crashes.

I have uninstalled and reinstalled the extension, but still have the issue.

After much trial and error, here is something I've noticed.  Not sure if this has anything to do with the issue, but when my project references Microsoft.NETCore.Platforms 3.1.0 (which has vulnerabilities according to JFrog), Visual Studio will crash when I open the JFrog window.  However, if I upgrade Microsoft.NETCore.Platforms to 3.1.4 (which does NOT have vulnerabilities), I can open the JFrog window without any problems.

**Comment by eyalbe4** [comment]
Thanks so much for investigating and reporting this issue @app2eds.
Will you be able to share with us a sample project that reproduces this issue through GitHub?

**Comment by jigar61** [comment]
I am having the same issue. The output window shows that the scan completes successfully and the json is returned but the treeview struggles to load and crashes VS 2019.

**Comment by eyalbe4** [comment]
@app2eds and @jigar61 - 
Thanks for raising this issue. We believe https://github.com/jfrog/jfrog-visual-studio-extension/pull/16 fixes the issue. We'll get a patch released soon.

**Comment by RobiNino** [comment]
Hi @app2eds and @jigar61 ,
We just released version 1.0.7 of the extension that includes a fix to this issue.
We'd appreciate your feedback for it.
Thanks

**Comment by jigar61** [comment]
Seems to work for me now.

**Comment by eyalbe4** [comment]
Thanks for the feedback @jigar61!
