### ISSUE TITLE
[Enhancement]Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by JaredShaver** [jfrog/jfrog-visual-studio-extension#4]
Please add support for Visual Studio 2019.  The extension is currently only for Visual Studio 2017.

**Comment by barbelity** [comment]
@JaredShaver, version 1.0.3 of the extension is now published, and compatible with Visual Studio 2019.
It would be great if you could share your opinion about it.

**Comment by JaredShaver** [comment]
I was able to get it installed and up and running.  Everything looks to be in working order.  Thank you for the update!
